### ISSUE TITLE
Not possible to run demo?

### ISSUE THREAD

**Issue by kevinrenskers** [composed-swift/Composed-Demo#1]
When I download the demo and open the project, Xcode tries to fetch the dependencies. Sadly that fails with the error `because root depends on Composed 0.0.0..<1.0.0 and root depends on Composed 1.0.0..<2.0.0, version solving failed.`

![Screen Shot 2020-05-02 at 00 38 11](https://user-images.githubusercontent.com/229384/80846654-40550a80-8c0d-11ea-879f-5eafd80f09c8.png)

**Comment by shaps80** [comment]
I saw this yesterday myself and released updates across all of the projects to fix. If you `git pull` try again it should work now. Sorry about that, I’d mistakenly forgotten to check the deps :)

Let me know if you have any further issues.

**Comment by kevinrenskers** [comment]
I'm not seeing any change, still the same error. There was also nothing new to pull?

**Comment by shaps80** [comment]
Interesting, I'll check it today. Its odd cause I'm using it myself without issue.

**Comment by shaps80** [comment]
@kevinrenskers ok apologies I see why now. I had the dependencies local and didn't realise I had a conflict where `ComposedMedia` and `ComposedMediaUI` (both WIP) were still referencing `Composed 0.0.0`.

Updated now, should work now. Please do let me know if you still have any issues, thanks.

**Comment by kevinrenskers** [comment]
It's not working.

![Screen Shot 2020-05-07 at 12 36 38](https://user-images.githubusercontent.com/229384/81285192-722bfe00-905f-11ea-8813-895e00f04b21.png)
![Screen Shot 2020-05-07 at 12 36 46](https://user-images.githubusercontent.com/229384/81285195-735d2b00-905f-11ea-8e21-9defbf2c4a35.png)

**Comment by kevinrenskers** [comment]
After running "update to latest swift packages" 3 times it finally resolved to a working state. Not sure what the hell is going on, I've never seen a package be this difficult 😅 

![Screen Shot 2020-05-07 at 12 39 33](https://user-images.githubusercontent.com/229384/81285514-f1213680-905f-11ea-9439-880409f4cca3.png)

**Comment by shaps80** [comment]
Odd. Glad its working for you now.
